services:
    newscoop_externallogin_plugin.lifecyclesubscriber:
        class: Newscoop\ExternalLoginPluginBundle\EventListener\LifecycleSubscriber
        arguments:
            - @service_container
        tags:
            - { name: kernel.event_subscriber}

    newscoop_externallogin_plugin.configure_menu_listener:
        class: Newscoop\ExternalLoginPluginBundle\EventListener\ConfigureMenuListener
        tags:
          - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments:
            - @translator

    newscoop_newscoop.simple_user_provider:
        class: Newscoop\ExternalLoginPluginBundle\Security\User\SimpleUserProvider
        arguments: ["@em", %simple_security%]
